[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos_axum = { workspace = true, optional = true }

anyhow = { workspace = true, optional = true }
axum_session = { workspace = true, optional = true }
axum_session_auth = { workspace = true, optional = true }
chrono.workspace = true
http.workspace = true
log.workspace = true
serde.workspace = true
sqlx = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { workspace = true, optional = true }

async-trait = { version = "*", optional = true }

cfg-if = "1"
const_format = "0.2.31"
markdown = { version = "1.0.0-alpha.16", optional = true }
quick-xml = { version = "0.31.0", optional = true }
openidconnect = { version = "3.3.0", optional = true }
tracing-subscriber = "0.3.18"

[dev-dependencies]
rand = "0.8.5"

[features]
default = []
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = [
    "leptos/ssr",
    "leptos_meta/ssr",
    "leptos_router/ssr",
    "dep:anyhow",
    "dep:async-trait",
    "dep:axum_session",
    "dep:axum_session_auth",
    "dep:markdown",
    "dep:quick-xml",
    "dep:leptos_axum",
    "dep:openidconnect",
    "dep:sqlx",
    "dep:tokio",
]

